import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,staticFile,delayRender,continueRender,useCurrentFrame,useVideoConfig,interpolate} from 'remotion';
import {z} from 'zod';
import {HUMANITARIANS as C} from '../tokens/humanitarians';

export const deepaDataSchema=z.object({beat:z.string(),frames:z.number(),audit:z.boolean().optional()});
/** Source-led, animated data-literacy diagrams with separate native landscape and portrait arrangements. */
export const DeepaDataDecisions:React.FC<z.infer<typeof deepaDataSchema>>=({beat,frames,audit=false})=>{
 const f=useCurrentFrame();const {width:w,height:h}=useVideoConfig();const p=h>w;const u=p?w/1080:w/1920;
 const [gate]=useState(()=>delayRender('HAI typography and data-decision graphics'));
 useEffect(()=>{Promise.all([['EB Garamond','EBGaramond-Regular.ttf'],['Montserrat','Montserrat-Medium.ttf']].map(async([name,file])=>{const face=new FontFace(name,`url(${staticFile('fonts/'+file)})`);await face.load();(document.fonts as any).add(face)})).then(()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{if(audit){const root=document.querySelector('[data-dd-root]')!;const rr=root.getBoundingClientRect();const rows=Array.from(root.querySelectorAll('[data-qc]')).map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return{text:el.textContent,x:(r.x-rr.x)*w/rr.width,y:(r.y-rr.y)*h/rr.height,w:r.width*w/rr.width,h:r.height*h/rr.height,font:parseFloat(s.fontSize),overflow:(el as HTMLElement).scrollWidth>(el as HTMLElement).clientWidth+2}});console.log('DD_QC '+JSON.stringify({beat,portrait:p,width:w,height:h,rows}))}continueRender(gate)})))},[gate]);
 const serif='EB Garamond, Georgia, serif',sans='Montserrat, Arial, sans-serif';const ink:string=C.INK,teal:string=C.TEAL,cream:string=C.CREAM,slate:string=C.SLATE,gold:string=C.GOLD;
 const fade=(step:number)=>interpolate(f,[Math.floor(frames*step),Math.floor(frames*step)+12],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
 const text=(s:string,size:number,color:string=ink,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:serif,fontSize:size*u,lineHeight:1.12,color,overflowWrap:'break-word',...extra}}>{s}</div>;
 const label=(s:string,color:string=slate,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:sans,fontSize:(p?27:24)*u,fontWeight:600,lineHeight:1.25,letterSpacing:'.035em',color,...extra}}>{s}</div>;
 const card=(children:React.ReactNode,step=0,extra:React.CSSProperties={})=><div style={{boxSizing:'border-box',background:'#FFFCF5',border:`${3*u}px solid ${slate}`,borderRadius:10*u,padding:24*u,opacity:fade(step),transform:`translateY(${(1-fade(step))*14*u}px)`,...extra}}>{children}</div>;
 const header=(n:string,title:string)=><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.13:.13)}}>{label(n,teal)}{text(title,p?68:78,ink,{fontWeight:600,marginTop:9*u})}</div>;
 const footer=<div style={{position:'absolute',left:w*.08,right:w*.08,bottom:h*(p?.055:.055),display:'flex',alignItems:'center',justifyContent:'space-between'}}>{label('@HumanitariansAI',ink,{fontSize:(p?23:20)*u})}<Img src={staticFile('hai-wordmark-outlined.svg')} style={{width:(p?210:240)*u,height:38*u,objectFit:'contain',objectPosition:'right'}}/></div>;
 const row=(items:string[],step=0)=> <div style={{display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:14*u}}>{items.map((v,i)=><React.Fragment key={v}>{card(<>{label(String(i+1).padStart(2,'0'),teal)}{text(v,p?35:33,ink,{marginTop:8*u})}</>,step+i*.1,{flex:1})}{p&&i<items.length-1&&<div style={{height:18*u,width:4*u,background:teal,alignSelf:'center'}}/>}</React.Fragment>)}</div>;
 const tiles=(count:number,missing=false)=> <div style={{display:'grid',gridTemplateColumns:`repeat(${p?4:8},1fr)`,gap:8*u}}>{Array.from({length:count},(_,i)=><div key={i} style={{height:48*u,background:missing&&[5,9,13,17].includes(i)?'transparent':([0,3,7].includes(i%8)?teal:'#D5CABB'),border:`2px solid ${missing&&[5,9,13,17].includes(i)?slate:'#FFFCF5'}`,opacity:.4+fade(i*.018)*.6}}/>)}</div>;
 const photo=(variant:number)=> <div style={{height:(p?175:190)*u,position:'relative',overflow:'hidden',background:['#DED4C4','#B8C6C2','#D5B991'][variant%3],border:`2px solid ${slate}`}}><div style={{position:'absolute',inset:0,background:variant%2?'linear-gradient(110deg,#26354455,#fff1)':'linear-gradient(0deg,#17212b66,transparent 65%)'}}/><div style={{position:'absolute',left:'42%',top:'22%',width:'17%',height:'19%',borderRadius:'50%',background:'#D6B08F'}}/><div style={{position:'absolute',left:'35%',top:'18%',width:'31%',height:'8%',background:gold,borderRadius:'50%'}}/><div style={{position:'absolute',left:'38%',top:'44%',width:'25%',height:'45%',background:variant%2?'#416970':'#243b51'}}/><div style={{position:'absolute',left:'34%',top:'49%',width:'33%',height:'12%',background:'#e8b84e',opacity:.9}}/></div>;
 const content:React.ReactNode=(()=>{switch(beat){
 case 'B00':return <><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.20:.20)}}>{label('HUMANITARIANS AI · STEM WEEK 4',teal)}{text('How Data Can Shape',p?74:96,ink,{fontWeight:600,marginTop:10*u})}{text('AI Decisions',p?81:105,teal,{fontWeight:600})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.52:.55)}}>{row(['Training examples','Learned patterns','System output'],.08)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.84:.84)}}>{text('Deepa Shenoy  ·  Liam narrating for Deepa',p?25:27,slate)}</div></>;
 case 'B01':return <>{header('01 · LEARNING FROM EXAMPLES','Patterns come from data')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.34:.36)}}>{card(<>{label('EXAMPLES')}{<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8*u,marginTop:16*u}}>{[0,1,2].map(i=><div key={i}>{photo(i)}</div>)}</div>}</>,.02)}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.69:.72),textAlign:'center'}}>{text('People define the task. The model learns patterns in examples.',p?34:38,teal)}</div></>;
 case 'B02':return <>{header('02 · DATA COMPOSITION','What is represented matters')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.36:.37),display:'flex',flexDirection:p?'column':'row',gap:20*u}}>{card(<>{label('EXAMPLES COLLECTED')}{tiles(24,false)}</>,.02,{flex:1})}{card(<>{label('POSSIBLE GAPS')}{tiles(24,true)}</>,.18,{flex:1,borderColor:teal})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.76:.76),textAlign:'center'}}>{text('Incomplete or unrepresentative data is a risk to evaluate, not an automatic outcome.',p?31:34)}</div></>;
 case 'B03':return <>{header('03 · SAMPLING + HISTORY','Data has a context')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.36:.39)}}>{row(['Which examples are collected?','How are they selected?','What historical patterns appear?'],.04)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.78:.75),textAlign:'center'}}>{label('DATA · MEASUREMENT · HUMAN CONTEXT',teal)}</div></>;
 case 'B04':return <>{header('04 · LABELS + MEASUREMENT','Does the label fit the idea?')}<div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.37:.39),display:'flex',flexDirection:p?'column':'row',alignItems:'center',gap:20*u}}>{card(<>{label('MEASURED')}{text('A proxy or label',p?38:42,ink,{marginTop:8*u})}</>,.04,{flex:1,textAlign:'center'})}{text('↔',60*u,teal)}{card(<>{label('INTENDED')}{text('The concept',p?38:42,ink,{marginTop:8*u})}</>,.18,{flex:1,textAlign:'center',borderColor:teal})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.79:.76),textAlign:'center'}}>{text('Check whether a measurement represents what it is meant to.',p?32:35)}</div></>;
 case 'B05':return <>{header('05 · TRAINING → USE','Conditions can change')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.37),display:'flex',flexDirection:p?'column':'row',gap:24*u}}>{card(<>{label('TRAINING CONDITIONS')}{photo(0)}{label('Examples represented',teal,{marginTop:8*u})}</>,.02,{flex:1})}{card(<>{label('REAL-WORLD USE')}{photo(2)}{label('Lighting · angle · equipment',teal,{marginTop:8*u})}</>,.18,{flex:1,borderColor:teal})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.83:.82),textAlign:'center'}}>{label('Distribution shift: evaluate possible mismatch',slate)}</div></>;
 case 'B06':return <>{header('FICTIONAL EXAMPLE','Safety equipment in photos')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.34:.35)}}>{card(<>{label('FICTIONAL EXAMPLE · ILLUSTRATIVE ONLY',C.CRIMSON)}<div style={{display:'flex',flexDirection:p?'column':'row',gap:12*u,marginTop:14*u}}>{[0,0,1].map((v,i)=><div key={i} style={{flex:1}}>{photo(v)}{label(['Similar workplace','Similar lighting','Similar equipment'][i],slate,{marginTop:6*u})}</div>)}</div><div style={{marginTop:15*u}}>{text('Train a vision system to recognize required safety equipment.',p?34:37)}</div></>,.03,{borderColor:C.CRIMSON})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.84:.82),textAlign:'center'}}>{label('No real company or deployed system is described.',slate)}</div></>;
 case 'B07':return <>{header('FICTIONAL EXAMPLE · CONTINUED','What if conditions differ?')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.37),display:'flex',flexDirection:p?'column':'row',gap:16*u}}>{['GLARE','NEW CAMERA ANGLE','DIFFERENT GEAR'].map((x,i)=>card(<>{label(x,teal)}{photo(i+1)}</>,.04+i*.13,{flex:1}))}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.82:.80),textAlign:'center'}}>{text('Patterns learned in represented settings may not work the same way elsewhere.',p?32:37)}</div></>;
 case 'B08':return <>{header('06 · EVALUATION','One score cannot show everything')}<div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.36:.38),textAlign:'center'}}>{card(<>{label('OVERALL RESULT',teal)}{text('One summary view',p?40:46,ink,{marginTop:8*u})}</>,.02)}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.60:.63)}}>{row(['Relevant conditions','Relevant groups','Meaningful differences'],.20)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.84:.85),textAlign:'center'}}>{label('NO INVENTED SCORES · EXAMINE INTENDED USE',slate)}</div></>;
 case 'B09':return <>{header('07 · RESPONSIBLE EVALUATION','Review, test, investigate')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.39)}}>{row(['Review collection + representation','Check labels + measurements','Test relevant conditions','Investigate differences'],.03)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.87:.85),textAlign:'center'}}>{label('Improve data, model design, or evaluation where appropriate',teal)}</div></>;
 case 'B10':return <>{header('08 · AFTER DEPLOYMENT','Monitor and keep learning')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.37:.40),display:'flex',flexDirection:p?'column':'row',alignItems:'center',gap:18*u}}>{card(<>{label('USE')}{text('Observe changing conditions',p?35:38,ink,{marginTop:8*u})}</>,.03,{flex:1})}{text('↻',65*u,teal)}{card(<>{label('MONITOR')}{text('Recheck performance',p?35:38,ink,{marginTop:8*u})}</>,.17,{flex:1,borderColor:teal})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.73:.75),textAlign:'center'}}>{text('Testing and mitigation can reduce identified problems; they cannot guarantee that every source of bias or error is gone.',p?32:36,C.CRIMSON)}</div></>;
 default:return <><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.19:.20)}}>{label('BEGINNER TAKEAWAY · HUMANITARIANS AI',teal)}{text('AI outputs reflect more than algorithms.',p?65:80,ink,{fontWeight:600,marginTop:15*u})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.49:.53)}}>{p?<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14*u}}>{['Data','Measurements','Assumptions','Evaluation','Conditions of use'].map((x,i)=>card(<>{label(String(i+1).padStart(2,'0'),teal)}{text(x,31,ink,{marginTop:5*u})}</>,.06+i*.06,{padding:15*u,minHeight:112*u,display:'flex',flexDirection:'column',justifyContent:'center'}))}</div>:row(['Data','Measurements','Assumptions','Evaluation','Conditions of use'],.06)}</div>{!p&&<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*.83,display:'flex',justifyContent:'space-between',alignItems:'center'}}>{text('Deepa Shenoy',33)}{label('Liam narrating for Deepa',slate)}</div>}</>;
 }})();
 return <AbsoluteFill data-dd-root style={{background:beat==='B00'?'#F4F0E7':cream,color:ink,fontFamily:serif,overflow:'hidden'}}><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*.06,display:'flex',justifyContent:'space-between',alignItems:'center'}}>{text('Deepa Shenoy',p?22:20,slate)}{label('DATA · DECISIONS',teal,{fontSize:(p?19:17)*u})}</div>{content}{footer}</AbsoluteFill>;
};
