import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,staticFile,delayRender,continueRender,useCurrentFrame,useVideoConfig,interpolate} from 'remotion';
import {z} from 'zod';
import {HUMANITARIANS as C} from '../tokens/humanitarians';

export const deepaWeek3WorkflowSchema=z.object({beat:z.string(),frames:z.number(),audit:z.boolean().optional()});
/** Film-as-code workflow diagrams, composed independently for landscape and portrait. */
export const DeepaWeek3Workflow:React.FC<z.infer<typeof deepaWeek3WorkflowSchema>>=({beat,frames,audit=false})=>{
 const f=useCurrentFrame();const {width:w,height:h}=useVideoConfig();const p=h>w;const u=p?w/1080:w/1920;
 const [gate]=useState(()=>delayRender('HAI fonts and Week 3 workflow visuals'));
 useEffect(()=>{Promise.all([['EB Garamond','EBGaramond-Regular.ttf'],['Montserrat','Montserrat-Medium.ttf']].map(async([name,file])=>{const face=new FontFace(name,`url(${staticFile('fonts/'+file)})`);await face.load();(document.fonts as any).add(face)})).then(()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{if(audit){const root=document.querySelector('[data-w3-root]')!;const rr=root.getBoundingClientRect();const sx=w/rr.width,sy=h/rr.height;const rows=Array.from(root.querySelectorAll('[data-qc]')).map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return{text:el.textContent,x:(r.x-rr.x)*sx,y:(r.y-rr.y)*sy,w:r.width*sx,h:r.height*sy,font:parseFloat(s.fontSize),scrollOverflow:(el as HTMLElement).scrollWidth>(el as HTMLElement).clientWidth+2}});console.log('W3_QC '+JSON.stringify({beat,portrait:p,width:w,height:h,rows}))}continueRender(gate)})))},[gate]);
 const serif='EB Garamond, Georgia, serif',sans='Montserrat, Arial, sans-serif';
 const fade=(step:number)=>interpolate(f,[Math.floor(frames*step),Math.floor(frames*step)+12],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
 const txt=(s:string,n:number,color:string=C.INK,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:serif,fontSize:n*u,lineHeight:1.12,color,overflowWrap:'break-word',...extra}}>{s}</div>;
 const lab=(s:string,color:string=C.SLATE,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:sans,fontWeight:600,fontSize:(p?25:23)*u,lineHeight:1.2,color,letterSpacing:'.035em',...extra}}>{s}</div>;
 const card=(children:React.ReactNode,step=0,extra:React.CSSProperties={})=><div style={{boxSizing:'border-box',padding:(p?25:28)*u,border:`${2.5*u}px solid ${C.SLATE}`,borderRadius:14*u,background:'#FFFCF5',opacity:fade(step),transform:`translateY(${(1-fade(step))*12*u}px)`,...extra}}>{children}</div>;
 const arrow=(vertical=p)=><div aria-hidden style={{position:'relative',flex:'0 0 auto',width:(vertical?4:44)*u,height:(vertical?40:4)*u,background:C.TEAL,borderRadius:8*u}}><span style={vertical?{position:'absolute',bottom:-1*u,left:-5*u,width:11*u,height:11*u,borderBottom:`${3*u}px solid ${C.TEAL}`,borderRight:`${3*u}px solid ${C.TEAL}`,transform:'rotate(45deg)'}:{position:'absolute',right:-1*u,top:-5*u,width:11*u,height:11*u,borderTop:`${3*u}px solid ${C.TEAL}`,borderRight:`${3*u}px solid ${C.TEAL}`,transform:'rotate(45deg)'}}/></div>;
 const header=(kicker:string,title:string)=><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.125:.15)}}>{lab(kicker,C.TEAL)}{txt(title,p?57:67,C.INK,{fontWeight:600,marginTop:9*u})}</div>;
 const footer=beat!=='B08'&&<div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.92:.91),display:'flex',flexDirection:p?'column':'row',alignItems:p?'flex-start':'center',justifyContent:'space-between',gap:8*u}}>{txt('@HumanitariansAI',p?25:22,C.INK,{fontFamily:sans})}<Img src={staticFile('hai-wordmark-outlined.svg')} style={{width:(p?190:220)*u,height:34*u,objectFit:'contain',objectPosition:'left'}}/></div>;
 const content:React.ReactNode=(()=>{switch(beat){
 case 'B00':return <>
  <div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.20:.20)}}>{lab('WEEK 3 · PERSONAL PROGRESS UPDATE',C.TEAL)}{txt('Learning the Brutalist',p?75:91,C.INK,{fontWeight:600,marginTop:12*u})}{txt('Film-as-Code Workflow',p?68:85,C.TEAL,{fontWeight:600})}</div>
  <div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.48:.53),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'space-between',gap:22*u}}>{card(<>{lab('LEARNING MATERIAL')}{txt('Ideas become a workflow',p?35:32,C.INK,{marginTop:8*u})}</>,.04,{flex:1,width:p?'100%':'30%'})}{arrow()}{card(<>{lab('BRUTALIST')}{txt('Plan · build · review',p?35:32,C.INK,{marginTop:8*u})}</>,.2,{flex:1,width:p?'100%':'30%',borderColor:C.TEAL})}{arrow()}{card(<>{lab('MY HAI WORK')}{txt('Educational content',p?35:32,C.INK,{marginTop:8*u})}</>,.36,{flex:1,width:p?'100%':'30%'})}</div>
  <div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.84:.83)}}>{txt('Deepa Shenoy  ·  Liam narrating for Deepa',p?25:26,C.SLATE)}</div>
 </>;
 case 'B01':return <>{header('01 · TOOLKIT','A local production workflow')}<div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.33:.37),display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:18*u}}>{card(<>{lab('SOURCE TREE')}{txt('Builders + shared runtime',p?38:33,C.INK,{marginTop:10*u})}</>,.02,{flex:1})}{arrow()}{card(<>{lab('SETUP / DOCTOR')}{txt('Check ready dependencies',p?38:33,C.INK,{marginTop:10*u})}</>,.22,{flex:1,borderColor:C.TEAL})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.72:.70),display:'flex',justifyContent:'center',gap:12*u,flexWrap:'wrap'}}>{['AI Explainer','CLI Explainer','Deep Explainer'].map((x,i)=><div key={x}>{card(lab(x,C.SLATE),.34+i*.10,{padding:16*u})}</div>)}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.86:.84),textAlign:'center'}}>{lab('LEARNING HOW THE PIECES FIT TOGETHER')}</div></>;
 case 'B02':return <>{header('02 · FIRST PROJECT','The Beat Sheet is the score')}<div style={{position:'absolute',left:w*.10,right:w*.10,top:h*(p?.30:.32),display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:(p?8:12)*u}}>{[['NARRATION','Words'],['BEATS','Moments'],['VISUALS','Scenes'],['TIMING','Audio clock'],['RENDER','Review cut']].map((a,i)=><React.Fragment key={a[0]}>{card(<>{p?<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12*u}}>{lab(a[0],i===3?C.TEAL:C.SLATE)}{txt(a[1],27,C.INK)}</div>:<>{lab(a[0],i===3?C.TEAL:C.SLATE)}{txt(a[1],29,C.INK,{marginTop:9*u})}</>}</>,.04+i*.07,{flex:1,textAlign:'center',padding:(p?12:18)*u})}{i<4&&arrow()}</React.Fragment>)}</div><div style={{position:'absolute',left:w*.15,right:w*.15,top:h*(p?.73:.72),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:12*u}}>{card(<>{lab('RENDERED')}{txt('Technical milestone',p?30:30,C.INK,{marginTop:5*u})}</>,.42,{flex:1,textAlign:'center',padding:(p?16:24)*u})}{arrow()}{card(<>{lab('HUMAN REVIEW',C.TEAL)}{txt('Editorial approval',p?30:30,C.INK,{marginTop:5*u})}</>,.55,{flex:1,borderColor:C.TEAL,textAlign:'center',padding:(p?16:24)*u})}</div></>;
 case 'B03':return <>{header('03 · COMPOSITION','Two formats, composed natively')}<div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.27:.32),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:12*u}}>{card(<>{lab('16:9 · LANDSCAPE')}{divFrame(false)}</>,.02,{flex:1,width:p?'100%':'46%',borderColor:C.TEAL,textAlign:'center'})}{card(<>{lab('9:16 · PORTRAIT',C.TEAL)}{divFrame(true)}</>,.22,{flex:1,width:p?'100%':'34%',borderColor:C.TEAL,textAlign:'center'})}</div>{!p&&<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*.81,textAlign:'center'}}>{txt('A shared story can use different visual arrangements.',33,C.INK)}</div>}</>;
 case 'B04':return <>{header('04 · CLI EXPLAINER','Story structure ≠ interface skin')}<div style={{position:'absolute',left:w*.10,right:w*.10,top:h*(p?.31:.34),display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:20*u}}>{card(<>{lab('NARRATIVE SPINE',C.TEAL)}<div style={{display:'flex',flexDirection:'column',gap:7*u,marginTop:14*u}}>{['Problem','Ask','Code + output','Revision','Improved output','Summary · handoff · outro'].map((x,i)=><div key={x} style={{opacity:fade(.05+i*.08)}}>{txt(x,p?31:27,C.INK)}</div>)}</div></>,.02,{flex:1})}{arrow()}{card(<>{lab('INTERFACE SKIN')}{txt('A separate visual layer',p?38:34,C.INK,{marginTop:13*u})}<div style={{display:'flex',gap:10*u,marginTop:22*u}}>{['CLI','CODE','OUTPUT'].map((x,i)=><div key={x}>{card(lab(x,C.TEAL),.24+i*.11,{padding:12*u})}</div>)}</div></>,.28,{flex:1,borderColor:C.TEAL})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.84:.81),textAlign:'center'}}>{lab('THE SEQUENCE STAYS; THE SKIN CAN CHANGE')}</div></>;
 case 'B05':return <>{header('05 · DEPTH + DURATION','Depth follows linked ideas')}<div style={{position:'absolute',left:w*.10,right:w*.10,top:h*(p?.32:.34),display:'flex',flexDirection:p?'column':'row',alignItems:'center',gap:19*u}}>{card(<>{lab('ACT 1')}{txt('Mechanism',p?37:33,C.INK,{marginTop:8*u})}</>,.02,{flex:1,textAlign:'center'})}{arrow()}{card(<>{lab('ACT 2',C.TEAL)}{txt('Connected mechanism',p?37:33,C.INK,{marginTop:8*u})}</>,.16,{flex:1,textAlign:'center',borderColor:C.TEAL})}{arrow()}{card(<>{lab('ACT 3')}{txt('Synthesis',p?37:33,C.INK,{marginTop:8*u})}</>,.30,{flex:1,textAlign:'center'})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.71:.69)}}>{lab('DURATION EMERGES FROM WHAT EACH BEAT NEEDS',C.SLATE)}<div style={{height:16*u,marginTop:18*u,background:'#DED4C4',borderRadius:9*u,overflow:'hidden'}}><div style={{width:`${Math.round(fade(.42)*100)}%`,height:'100%',background:C.TEAL}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:9*u}}>{lab('NARRATION TIMING')}{lab('INFORMATION IN THE BEAT')}</div></div></>;
 case 'B06':return <>{header('06 · AUDIO-FIRST','Narration is the production clock')}<div style={{position:'absolute',left:w*.11,right:w*.11,top:h*(p?.30:.34),display:'flex',flexDirection:p?'column':'row',alignItems:'center',gap:20*u}}>{card(<>{lab('WAVEFORM',C.TEAL)}<div style={{height:110*u,display:'flex',alignItems:'center',gap:5*u,marginTop:12*u}}>{Array.from({length:24},(_,i)=><div key={i} style={{width:4*u,height:(18+((i*13)%61))*u,background:C.TEAL,opacity:.4+fade(.03+i*.025)*.6,borderRadius:3*u}}/>)}</div></>,.02,{flex:1})}{arrow()}{card(<>{lab('BEAT SLOTS')}{['B01','B02','B03'].map((x,i)=><div key={x} style={{display:'flex',alignItems:'center',gap:10*u,marginTop:12*u}}>{card(lab(x,C.TEAL),.1+i*.08,{padding:10*u})}<div style={{width:(p?340:150)*u,height:11*u,background:i===1?C.GOLD:'#D7CDBD',borderRadius:5*u}}/></div>)}</>,.22,{flex:1})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.76:.73),textAlign:'center'}}>{txt('Revise one slot; neighboring beats can stay in place.',p?36:34,C.INK)}</div></>;
 case 'B07':return <>{header('07 · QC IN MY HAI WORK','Checks support judgment')}<div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.30:.32),display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:17*u}}>{card(<>{lab('CLAIM')}{txt('What does the visual support?',p?34:30,C.INK,{marginTop:9*u})}</>,.02,{flex:1})}{arrow()}{card(<>{lab('EVIDENCE',C.TEAL)}{txt('Visuals serve the actual idea.',p?34:30,C.INK,{marginTop:9*u})}</>,.12,{flex:1,borderColor:C.TEAL})}</div><div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.51:.57),display:'grid',gridTemplateColumns:p?'1fr 1fr':'repeat(4,1fr)',gap:12*u}}>{['Resolution','Branding','Safe areas','Decode'].map((x,i)=><React.Fragment key={x}>{card(<>{lab('✓',C.TEAL)}{txt(x,p?28:27,C.INK,{marginTop:5*u})}</>,.24+i*.08,{textAlign:'center',padding:(p?12:17)*u})}</React.Fragment>)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.76:.77),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:12*u}}>{card(<>{lab('MACHINE-CHECKABLE',C.SLATE)}{txt('Technical properties',p?28:26,C.INK,{marginTop:4*u})}</>,.47,{flex:1,textAlign:'center',padding:(p?15:24)*u})}{arrow()}{card(<>{lab('HUMAN REVIEW',C.TEAL)}{txt('Editorial judgment',p?28:26,C.INK,{marginTop:4*u})}</>,.58,{flex:1,textAlign:'center',borderColor:C.TEAL,padding:(p?15:24)*u})}</div></>;
 default:return <>
  <div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.24:.20)}}>{lab('WEEK 3 · HUMANITARIANS AI',C.TEAL)}{txt('Learning the Brutalist',p?72:88,C.INK,{fontWeight:600,marginTop:12*u})}{txt('Film-as-Code Workflow',p?66:80,C.TEAL,{fontWeight:600})}</div>
  <div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.59:.59),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'space-between',gap:20*u}}>{txt('Deepa Shenoy',p?43:39,C.INK)}{lab('Liam narrating for Deepa',C.SLATE)}</div>
  <div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.77:.78),display:'flex',flexDirection:p?'column':'row',alignItems:p?'flex-start':'center',justifyContent:'space-between',gap:15*u}}>{txt('@HumanitariansAI',p?33:28,C.INK,{fontFamily:sans})}<Img src={staticFile('hai-wordmark-outlined.svg')} style={{width:(p?250:285)*u,height:45*u,objectFit:'contain',objectPosition:'left'}}/></div>
 </>;
 }})();
 function divFrame(vertical:boolean){return <div style={{width:p?(vertical?'42%':'74%'):(vertical?'26%':'100%'),marginLeft:'auto',marginRight:'auto',aspectRatio:vertical?'9 / 16':'16 / 9',marginTop:13*u,border:`${3*u}px solid ${C.SLATE}`,borderRadius:9*u,background:'#F3EBDD',display:'flex',alignItems:'center',justifyContent:'center',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',left:'12%',right:'12%',top:'24%',height:'13%',background:C.TEAL,opacity:.18,borderRadius:6*u}}/><div style={{position:'absolute',left:'18%',right:'18%',top:'48%',height:'6%',background:C.TEAL,opacity:.38,borderRadius:6*u}}/><div style={{position:'absolute',left:'25%',right:'25%',top:'64%',height:'6%',background:C.GOLD,borderRadius:6*u}}>{/* native layout diagram */}</div>{lab(vertical?'STACKED STORY':'WIDE STORY',C.SLATE,{fontSize:(p?19:17)*u,position:'absolute',bottom:9*u,left:9*u})}</div>}
 return <AbsoluteFill data-w3-root style={{background:C.CREAM,color:C.INK,fontFamily:serif,overflow:'hidden'}}><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*(p?.06:.05),display:'flex',justifyContent:'space-between',alignItems:'center'}}>{txt('Deepa Shenoy',p?25:23,C.SLATE)}{lab('WEEK 3 · PROGRESS',C.TEAL)}</div>{content}{footer}</AbsoluteFill>;
};
