import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,staticFile,delayRender,continueRender,useCurrentFrame,useVideoConfig,interpolate} from 'remotion';
import {z} from 'zod';
import {HUMANITARIANS as C} from '../tokens/humanitarians';

export const deepaSubmissionSchema=z.object({beat:z.string(),frames:z.number(),audit:z.boolean().optional()});
/** Content #8 personal progress visuals; evidence-based local file workflow, portrait-native layouts. */
export const DeepaSubmissionProgress:React.FC<z.infer<typeof deepaSubmissionSchema>>=({beat,frames,audit=false})=>{
 const f=useCurrentFrame();const {width:w,height:h}=useVideoConfig();const p=h>w;const u=p?w/1080:w/1920;
 const [gate]=useState(()=>delayRender('HAI typography and submission workflow graphics'));
 useEffect(()=>{Promise.all([['EB Garamond','EBGaramond-Regular.ttf'],['Montserrat','Montserrat-Medium.ttf']].map(async([name,file])=>{const face=new FontFace(name,`url(${staticFile('fonts/'+file)})`);await face.load();(document.fonts as any).add(face)})).then(()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{if(audit){const root=document.querySelector('[data-sp-root]')!;const rr=root.getBoundingClientRect();const rows=Array.from(root.querySelectorAll('[data-qc]')).map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return{text:el.textContent,x:(r.x-rr.x)*w/rr.width,y:(r.y-rr.y)*h/rr.height,w:r.width*w/rr.width,h:r.height*h/rr.height,font:parseFloat(s.fontSize),overflow:(el as HTMLElement).scrollWidth>(el as HTMLElement).clientWidth+2}});console.log('SP_QC '+JSON.stringify({beat,portrait:p,width:w,height:h,rows}))}continueRender(gate)})))},[gate]);
 const serif='EB Garamond, Georgia, serif',sans='Montserrat, Arial, sans-serif',ink:string=C.INK,teal:string=C.TEAL,cream:string=C.CREAM,navy:string=C.SLATE,gold:string=C.GOLD;
 const fade=(step:number)=>interpolate(f,[Math.floor(frames*step),Math.floor(frames*step)+10],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
 const txt=(s:string,n:number,color:string=ink,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:serif,fontSize:n*u,lineHeight:1.12,color,overflowWrap:'break-word',...extra}}>{s}</div>;
 const lab=(s:string,color:string=navy,extra:React.CSSProperties={})=><div data-qc style={{fontFamily:sans,fontSize:(p?26:23)*u,fontWeight:600,lineHeight:1.2,letterSpacing:'.025em',color,...extra}}>{s}</div>;
 const card=(children:React.ReactNode,step=0,extra:React.CSSProperties={})=><div style={{boxSizing:'border-box',background:'#FFFCF5',border:`${2.5*u}px solid ${navy}`,borderRadius:12*u,padding:22*u,opacity:fade(step),transform:`translateY(${(1-fade(step))*12*u}px)`,...extra}}>{children}</div>;
 const header=(k:string,t:string)=><div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.14:.14)}}>{lab(k,teal)}{txt(t,p?66:77,ink,{fontWeight:600,marginTop:9*u})}</div>;
 const footer=<div style={{position:'absolute',left:w*.08,right:w*.08,bottom:h*.055,display:'flex',alignItems:'center',justifyContent:'space-between'}}>{lab('@HumanitariansAI',ink,{fontSize:(p?23:20)*u})}<Img src={staticFile('hai-wordmark-outlined.svg')} style={{width:(p?205:235)*u,height:38*u,objectFit:'contain',objectPosition:'right'}}/></div>;
 const flow=(items:string[],step=0)=> <div style={{display:'flex',flexDirection:p?'column':'row',alignItems:'stretch',gap:13*u}}>{items.map((x,i)=><React.Fragment key={x}>{card(<>{lab(String(i+1).padStart(2,'0'),teal)}{txt(x,p?32:31,ink,{marginTop:8*u})}</>,step+i*.08,{flex:1})}{p&&i<items.length-1&&<div style={{height:15*u,width:4*u,background:teal,alignSelf:'center',opacity:fade(step+i*.08)}}/>}</React.Fragment>)}</div>;
 const folder=(name:string,color=teal,extra:React.CSSProperties={})=><div style={{position:'relative',...extra}}><div style={{position:'absolute',top:-13*u,left:12*u,width:72*u,height:17*u,background:color,borderRadius:`6px 6px 0 0`}}/><div style={{border:`3px solid ${color}`,borderRadius:8*u,padding:18*u,background:'#FFFCF5'}}>{lab(name,color)}</div></div>;
 const file=(kind:string,color=navy)=><div style={{border:`2px solid ${color}`,borderRadius:6*u,background:'#FFFCF5',padding:`10px ${12*u}px`,minWidth:80*u}}>{lab(kind,color,{fontSize:(p?18:17)*u})}</div>;
 const formatFrame=(portrait:boolean)=><div style={{width:p?(portrait?160:250)*u:(portrait?116:315)*u,aspectRatio:portrait?'9 / 16':'16 / 9',border:`3px solid ${navy}`,borderRadius:6*u,background:'#DED4C4',position:'relative',overflow:'hidden',flex:'0 0 auto'}}><div style={{position:'absolute',inset:0,background:'linear-gradient(140deg,#1F4E5F22,#F3A71222)'}}/><div style={{position:'absolute',left:'15%',right:'15%',top:'22%',height:'16%',background:teal,opacity:.28}}/><div style={{position:'absolute',left:'28%',right:'28%',top:'51%',height:'8%',background:gold}}/><div style={{position:'absolute',left:'20%',right:'20%',top:'68%',height:'6%',background:navy,opacity:.7}}/></div>;
 const content:React.ReactNode=(()=>{switch(beat){
 case 'B00':return <><div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.21:.21)}}>{lab('WEEK 4 · PERSONAL PROGRESS',teal)}{txt('Preparing My Brutalist',p?69:91,ink,{fontWeight:600,marginTop:9*u})}{txt('Videos for Submission',p?65:84,teal,{fontWeight:600})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.53:.56),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:24*u}}>{formatFrame(false)}{formatFrame(true)}{!p&&<div style={{width:270*u}}>{folder('LOCAL PACKAGE',teal)}</div>}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.86:.84)}}>{txt('Deepa Shenoy · Liam narrating for Deepa',p?25:26,navy)}</div></>;
 case 'B01':return <>{header('01 · VIDEO PAIRS','Two native compositions')}<div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.34:.36),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:24*u}}>{card(<>{lab('16:9 · LANDSCAPE',teal)}<div style={{display:'flex',justifyContent:'center',marginTop:12*u}}>{formatFrame(false)}</div>{lab('Wide visual hierarchy',navy,{marginTop:8*u})}</>,.03,{flex:1,textAlign:'center'})}{card(<>{lab('9:16 · PORTRAIT',teal)}<div style={{display:'flex',justifyContent:'center',marginTop:12*u}}>{formatFrame(true)}</div>{lab('Rearranged for the tall frame',navy,{marginTop:8*u})}</>,.18,{flex:1,textAlign:'center',borderColor:teal})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.84:.84),textAlign:'center'}}>{lab('COMPOSED FOR EACH FORMAT · NOT CROPPED',navy)}</div></>;
 case 'B02':return <>{header('02 · HUMAN REVIEW GATES','People review at two stages')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.38)}}>{flow(['Narration review','Render both versions','Watch both complete cuts','Approve the pair'],.03)}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.88:.85),textAlign:'center'}}>{lab('AUTOMATION SUPPORTS · PEOPLE APPROVE',teal)}</div></>;
 case 'B03':return <>{header('03 · QUALITY CONTROL','Checks support the review')}<div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.34:.36),display:'grid',gridTemplateColumns:p?'1fr 1fr':'repeat(4,1fr)',gap:12*u}}>{['Resolution','Frames + layout','Typography','Safe areas','Audio + loudness','Full decode','Master properties'].map((x,i)=>card(<>{lab(String(i+1).padStart(2,'0'),teal)}{txt(x,p?27:29,ink,{marginTop:6*u})}</>,.02+i*.055,{textAlign:'center',padding:(p?16:18)*u,minHeight:(p?115:105)*u}))}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.84:.83),textAlign:'center'}}>{lab('PROJECT-APPROPRIATE CHECKS · HUMAN JUDGMENT',navy)}</div></>;
 case 'B04':return <>{header('04 · LOCAL SUBMISSION SET','One folder per content piece')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.34:.37),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:18*u}}>{card(<>{lab('LOCAL SUBMISSION FOLDER',teal)}<div style={{display:'grid',gridTemplateColumns:p?'repeat(4,1fr)':'repeat(4,1fr)',gap:8*u,marginTop:14*u}}>{Array.from({length:7},(_,i)=>folder(String(i+1).padStart(2,'0'),i===6?teal:navy))}</div></>,.03,{flex:1})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.79:.78),textAlign:'center'}}>{lab('SEVEN NUMBERED CONTENT FOLDERS',navy)}</div></>;
 case 'B05':return <>{header('05 · KEEP DESTINATIONS CLEAR','Separate videos and documentation')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.34:.38),display:'flex',flexDirection:p?'column':'row',gap:20*u}}>{card(<>{folder('Video/',teal)}<div style={{display:'flex',gap:8*u,marginTop:20*u}}>{file('16:9 MP4',teal)}{file('9:16 MP4',teal)}</div><div style={{marginTop:12*u}}>{lab('APPROVED VIDEO FILES',navy)}</div></>,.03,{flex:1})}{card(<>{folder('GitHub/',navy)}<div style={{display:'flex',flexWrap:'wrap',gap:8*u,marginTop:20*u}}>{file('.md',navy)}{file('16:9 Beat Sheet',navy)}{file('9:16 Beat Sheet',navy)}</div><div style={{marginTop:12*u}}>{lab('PROJECT DOCUMENTATION',navy)}</div></>,.18,{flex:1,borderColor:teal})}</div></>;
 case 'B06':return <>{header('06 · PACKAGE CHECK','Check names, counts, and contents')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.34:.37)}}>{flow(['Two MP4s: landscape + portrait','Both Beat Sheets','Relevant Markdown','Zero MP4s in GitHub'],.03)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.88:.84),textAlign:'center'}}>{lab('A SHORT CHECKLIST BEFORE SUBMISSION',teal)}</div></>;
 case 'B07':return <>{header('07 · FILE INTEGRITY','Compare source and copy')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.36:.39),display:'flex',flexDirection:p?'column':'row',alignItems:'center',justifyContent:'center',gap:22*u}}>{card(<>{lab('APPROVED SOURCE',navy)}{file('MP4',teal)}</>,.03,{flex:1,textAlign:'center'})}{txt('↔',55,teal)}{card(<>{lab('COPIED FILE',navy)}{file('MP4',teal)}</>,.18,{flex:1,textAlign:'center'})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.72:.72),textAlign:'center'}}>{card(<>{lab('SHA-256 FINGERPRINTS MATCH',teal)}{txt('A practical check that the copy matches its source.',p?31:36,ink,{marginTop:10*u})}</>,.34,{borderColor:teal})}</div></>;
 case 'B08':return <>{header('08 · CONTENT #7 PACKAGE','A verified local example')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.38),display:'flex',flexDirection:p?'column':'row',gap:18*u}}>{card(<>{folder('Video/',teal)}{lab('2 MP4s · 16:9 + 9:16',navy,{marginTop:18*u})}<div style={{marginTop:12*u}}>{lab('Copied hashes match sources',teal)}</div></>,.03,{flex:1})}{card(<>{folder('GitHub/',navy)}{lab('2 Beat Sheets + Markdown',navy,{marginTop:18*u})}<div style={{marginTop:12*u}}>{lab('0 MP4s',teal)}</div></>,.18,{flex:1,borderColor:teal})}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.85:.84),textAlign:'center'}}>{lab('COPY CHECKED · ORIGINALS LEFT IN PLACE',navy)}</div></>;
 case 'B09':return <>{header('09 · WHAT I LEARNED','A media project has many parts')}<div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.35:.38)}}>{flow(['Create','Review','QC','Organize','Document','Verify'],.02)}</div><div style={{position:'absolute',left:w*.12,right:w*.12,top:h*(p?.88:.85),textAlign:'center'}}>{txt('The film-as-code workflow connects them.',p?34:39,teal)}</div></>;
 case 'B10':return <>{header('10 · CURRENT STATUS','Preparing for submission')}<div style={{position:'absolute',left:w*.14,right:w*.14,top:h*(p?.40:.42),display:'flex',justifyContent:'center'}}>{card(<>{folder('LOCAL · IN PROGRESS',teal)}<div style={{marginTop:20*u}}>{lab('Materials organized and verified',navy)}</div><div style={{marginTop:12*u}}>{lab('Not uploaded · Not published',navy)}</div></>,.03,{width:p?'100%':'62%',borderColor:teal,textAlign:'center',padding:34*u})}</div></>;
 default:return <><div style={{position:'absolute',left:w*.09,right:w*.09,top:h*(p?.23:.21)}}>{lab('HUMANITARIANS AI · WEEK 4',teal)}{txt('From learning to a',p?69:85,ink,{fontWeight:600,marginTop:12*u})}{txt('structured production workflow',p?58:70,teal,{fontWeight:600})}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.51:.55)}}>{flow(['Produce','Review','Prepare'],.06)}</div><div style={{position:'absolute',left:w*.1,right:w*.1,top:h*(p?.82:.83),display:'flex',flexDirection:p?'column':'row',alignItems:p?'flex-start':'center',justifyContent:'space-between',gap:12*u}}>{txt('Deepa Shenoy',p?34:34)}{lab('Liam narrating for Deepa',navy)}</div></>;
 }})();
 return <AbsoluteFill data-sp-root style={{background:beat==='B00'?'#F4F0E7':cream,color:ink,fontFamily:serif,overflow:'hidden'}}><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*.06,display:'flex',justifyContent:'space-between',alignItems:'center'}}>{txt('Deepa Shenoy',p?22:20,navy)}{lab('PROGRESS · SUBMISSION',teal,{fontSize:(p?18:17)*u})}</div>{content}{footer}</AbsoluteFill>;
};
